### ISSUE TITLE
SIGPIPE not supported on windows

### ISSUE THREAD

**Issue by gcbsumid** [MikeHibbert/arweave-python-client#15]
**Describe the bug**
SIGPIPE is not supported on Windows. Uploading any transactions fail on windows. I've just made the following changes locally, so it's up to you guys however you would like to fix it. 

**Version Used**
My version is the latest version.

**Proposed Solution**
Put the SIGPIPE attempt in a try and ignore if it fails. 

```
try:
    from signal import signal, SIGPIPE, SIG_DFL
    signal(SIGPIPE, SIG_DFL)
except ImportError:  # If SIGPIPE is not available (win32),
    pass   
```

**Comment by MikeHibbert** [comment]
Ideally you could describe how to reproduce the bug and exactly where it is you've inserted this code?

Even better would be if you created a branch and submitted a pull request that we could integrate with our code quickly and you would gain contributor status too!

**Comment by gcbsumid** [comment]
Python version: 3.7.9
Unity Version: 2020.3.12f1
OS: Windows 10

To repro the bug, you can attempt to upload file using the get_upload() from transaction_uploader.py on Windows. Though I did not try uploading a small file, I assume it would hit the same issue. After installing the python arweave client, the following is good enough to repro the issue:

`from arweave.arweave_lib import Wallet, Transaction
from arweave.transaction_uploader import get_uploader

wallet = Wallet(jwk_file)

with open("my_mahoosive_file.dat", "rb", buffering=0) as file_handler:
    tx = Transaction(wallet, file_handler=file_handler, file_path="/some/path/my_mahoosive_file.dat")
    tx.add_tag('Content-Type', 'application/dat')
    tx.sign()
    
    uploader = get_uploader(tx, file_handler)

    while not uploader.is_complete:
        uploader.upload_chunk()

        logger.info("{}% complete, {}/{}".format(
            uploader.pct_complete, uploader.uploaded_chunks, uploader.total_chunks
        ))`

I've also created a PR, as requested. Please review when possible.

**Comment by MikeHibbert** [comment]
Thanks for the help and the PR, I've merged it in
