### ISSUE TITLE
Uploader doesn't work on Windows 10

### ISSUE THREAD

**Issue by joshbenaron** [MikeHibbert/arweave-python-client#19]
**Describe the bug**
On Windows 10, importing the uploader fails, due to it importing signal

**Version Used**
My version is 1.0.14

**To Reproduce**

```py
from arweave.transaction_uploader import get_uploader
```

The issue is in `transaction_uploader.py`:
```py
from signal import signal, SIGPIPE, SIG_DFL

signal(SIGPIPE, SIG_DFL)
```
Which causes `ImportError: cannot import name 'SIGPIPE' from 'signal' (C:\Python38\lib\signal.py)`

This post explains how it's not supported on Windows 10 - [explanation](https://stackoverflow.com/questions/58718659/cannot-import-name-sigpipe-from-signal-in-windows-10)

I'm not 100% sure what it does but I hope there's an alternative. FYI - by commenting those 2 lines out It works as expected with no errors

**Comment by joshbenaron** [comment]
I've just seen an old issue on it. Could you make a new release please?

**Comment by MikeHibbert** [comment]
Published new version to Pypi
