### ISSUE TITLE
use tx_anchor instead of wallets last_tx to enable multiple transactions per block

### ISSUE THREAD

**Issue by aidanok** [MikeHibbert/arweave-python-client#2]
https://github.com/MikeHibbert/arweave-python-client/blob/9b81df4629dd83eaaff43286994450a1f581e6cd/arweave/arweave_lib.py#L60 

This can use the /tx_anchor instead to set the last_tx field on a transaction,   

`last_tx` is named like because in legacy versions it had to be the wallets last tx, but in recent versions you can use any block hash from the last 50 blocks and then submit multiple last txs

**Comment by MikeHibbert** [comment]
Update the code at line 61 of arweave-python-client/arweave/arweave_lib.py to use tx_achor instead

A new module is also available form PyPi (version 0.9.1)
