### ISSUE TITLE
Unable to import SIGPIPE from signal on Windows

### ISSUE THREAD

**Issue by gregorypierce** [MikeHibbert/arweave-python-client#20]
**Describe the bug**
When using the library on Windows (because sometimes you just have to), you will encounter an error  in <module>
    from signal import signal, SIGPIPE, SIG_DFL

**Version Used**
My version is 'latest'

**To Reproduce**
1. from arweave import Wallet, Transaction
2. from arweave.transaction_uploader import get_uploader

**Expected behavior**
Clean import

**Additional context**
1. https://stackoverflow.com/questions/58718659/cannot-import-name-sigpipe-from-signal-in-windows-10

**Comment by MikeHibbert** [comment]
Have you just installed this module or has there been some time passed as this was fixed and included in the latest pip distro

https://github.com/MikeHibbert/arweave-python-client/blob/master/arweave/transaction_uploader.py

**Comment by gregorypierce** [comment]
Just installed it this morning via pip install.

**Comment by MikeHibbert** [comment]
perhaps for now you can do 

`pip install git+https://github.com/MikeHibbert/arweave-python-client.git`

This will install the latest code
