### ISSUE TITLE
arweave_lib portion erroring, but appears to still complete?

### ISSUE THREAD

**Issue by karmacnft** [MikeHibbert/arweave-python-client#21]
Running this query: [https://github.com/MikeHibbert/arweave-python-client#uploading-large-files](https://github.com/MikeHibbert/arweave-python-client#uploading-large-files)
 with: 

`from arweave.arweave_lib import Wallet, Transaction`

It throws an error in the response JSON but appears(?) to be OK and complete the transaction successfully.

The error is: 
`ERROR:arweave.arweave_lib:{"data": "eyduYW1lJzo....`

**Expected behavior**
I'm not sure of "expected" behavior, or if I may just be missing because it seems(?) it more of a warning, than an error maybe?

**Comment by MikeHibbert** [comment]
I have no way to tell as you didn't show how to reproduce the error
