### ISSUE TITLE
Transaction ID not valid for retrieving Uploaded Arweave data.

### ISSUE THREAD

**Issue by kingzley** [MikeHibbert/arweave-python-client#22]
Hello, 

I intend to retrieve link to uploaded data in this format: https://arweave.net/lOwhw7jABKgJXrtStVmU1tJaC5PR_Fk6QPekZ9ecrAk

Where _lOwhw7jABKgJXrtStVmU1tJaC5PR_Fk6QPekZ9ecrAk_ is the ID.

However, I can't do that with `get_last_transaction_id()`
It seems that is not valid for what I want and I notice it changes after a short while.

So how can I retrieve uploaded data with _arweave-python-client_, or is this not available?

Thank you.

**Comment by MikeHibbert** [comment]
@kingzley You should be able to get the transaction.id is from the newly created and sent transaction object you have created

The last transaction is not what it used to be and now does really mean what is called on the arweave network anymore

**Comment by kingzley** [comment]
@MikeHibbert Thank you so much. `transaction.id` works.
