### ISSUE TITLE
Dear developer, I have a question for you

### ISSUE THREAD

**Issue by ifczt** [MikeHibbert/arweave-python-client#24]
When I upload successfully, I visit the link. Why should I download it instead of displaying it in the browser?
like : https://arweave.net/J71RbRXKErAaLTV_ueVPYpcGfABUm_E9teLBnp3Kziw
like : https://arweave.net/vjpC_IhtSAlmDOjZAnU3hLienLinoaY4-m_QI6HvzQI
plz help me ~

**Comment by ProTrooper** [comment]
I think it is because you uploaded it as Binary files, not as images or something that your browser can run.

**Comment by MikeHibbert** [comment]
> 

You need to add a 'Content-Type' tag to the transaction before posting then it will know how to display the download in the browser

There are various mime modules for python you could use buy passing the file extension

**Comment by MikeHibbert** [comment]
marking as resolved
