### ISSUE TITLE
Data is uploaded incorrectly when uses_uploader=False

### ISSUE THREAD

**Issue by ldmberman** [MikeHibbert/arweave-python-client#26]
There is a bug where data passed directly to a `Transaction` object is not uploaded correctly. It computes `data_root` from the [Base64URL encoded](https://github.com/MikeHibbert/arweave-python-client/blob/master/arweave/arweave_lib.py#L115) data so the nodes do not recognize it and do not accept the original data.

[An example](https://arweave.net/tx/7AZJq7Dqjo1LHBfU69PIAmTSkK8iBM5mXP-0JJf9Izo). `data_root` computed from the raw data is `yiIbdak6AXJ17hGF5EJC_FpleCvd3pBe2c4jSZpRDVM` whereas the tx was signed with `XTcZfQOhQ0byq0NjAfJbYynVMyX6fkd4IBIfRR3S0IA` - the value consistent with computing `data_root` from a Base64URL encoded blob.

To fix the issue it should be sufficient to decode [here](https://github.com/MikeHibbert/arweave-python-client/blob/master/arweave/arweave_lib.py#L207) and [here](https://github.com/MikeHibbert/arweave-python-client/blob/master/arweave/arweave_lib.py#L210).

**Comment by MikeHibbert** [comment]
Thanks for heads up, fancy submitting a PR for some project credit?

**Comment by ldmberman** [comment]
Hi @MikeHibbert, thank you for the quick reply, opened [one](https://github.com/MikeHibbert/arweave-python-client/pull/27). What would you say to removing the older versions of the library from the package repositories?

**Comment by MikeHibbert** [comment]
I'll take a look and maybe remove some older ones but I'm uncertain about removing the more recent ones in it causes dependency issues.

What makes you think this is a thing that will help?

**Comment by ldmberman** [comment]
The motivation is to prevent people from uploading the wrong data.

**Comment by 0xEnrico** [comment]
@MikeHibbert please have a look at this explanation: https://github.com/0xEnrico/arweave-nft-uploader/issues/14#issuecomment-1004283529

Basically, if I understood well, only the arweave.net cache keeps the data, while the nodes discard it. That is, when/if the cache gets flushed, the data is gone if it was uploaded using the `data=` field in the constructor...

Seems to me a quite serious issue.
