### ISSUE TITLE
How to upload a png?

### ISSUE THREAD

**Issue by AKnownEntity** [MikeHibbert/arweave-python-client#29]
I'm trying to use this lib to upload a PNG to arweave, I have something like this:

```
image = cv2.imread('./build/images/0.png')
transaction = arweave.Transaction(arweave_wallet, data=image)
transaction.sign()
transaction.send()
```

But get an error:

```
AppData\Local\Programs\Python\Python310\lib\site-packages\arweave\arweave_lib.py", line 118, in __init__
    self.data = base64url_encode(data.encode('utf-8'))
AttributeError: 'numpy.ndarray' object has no attribute 'encode'
```

Any ideas how I could accomplish this?

Thanks

**Comment by MikeHibbert** [comment]
Looks like this line:

image = cv2.imread('./build/images/0.png')

returns a non-string object and instead creates a numpy.ndarray which needs to be converted to a string to be compatible
