### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by DanKamilov** [MikeHibbert/arweave-python-client#31]
Hello!

I use this code 

`
wallet_file_path = "mywallet.json"
wallet = arweave.Wallet(wallet_file_path)

with open('myPicture.jpg', 'rb') as file:
    data_file = file.read()

    transaction = Transaction(wallet, data=data_file)
    transaction.sign()
    c = transaction.send()
    print(c)
`

 9/10 times I get 'Connection reset by peer'. But during this 1 normal try I see some hash info like "yAq2A-AHCmXwyFSO_jzXNct_yPBUi8P3_ZdS_Dx3GoK7c3PGtg". But I don't see image in my ARDRIVE. What is a problem? What I do wrong?

**Comment by MikeHibbert** [comment]
I wouldn't have expected to see this in your ARDRIVE anyway. Its not supplying the needed tags etc. 

This module is not meant to be used in connection with that program

**Comment by DanKamilov** [comment]
> I wouldn't have expected to see this in your ARDRIVE anyway. Its not supplying the needed tags etc.
> 
> This module is not meant to be used in connection with that program

But how to get my arweave link after uploading file to my wallet account?
