### ISSUE TITLE
Load wallet directly with the wallet address 

### ISSUE THREAD

**Issue by olabanjy** [MikeHibbert/arweave-python-client#33]
I have my wallet address saved in aws secret manager. I can fetch the address at runtime but the wallet  __init__  method only allow loading the wallet from a file. Is there a way to load the Wallet with an address ?

**Comment by MikeHibbert** [comment]
If you write the code to add the feature then it will do it.

There was never any support for password/wallet/identity management so this is not part of the module. Please feel free to fork and add the feature if your up to it
