### ISSUE TITLE
arweave.arweave_lib.ArweaveTransactionException: Too Many Requests

### ISSUE THREAD

**Issue by sungkhum** [MikeHibbert/arweave-python-client#35]
**Describe the bug**
Got an error: arweave.arweave_lib.ArweaveTransactionException: Too Many Requests

**Version Used**
Current

**To Reproduce**
Upload a lot of images one after the other (this time just got to 51)

**Expected behavior**
Upload all my images without any issues

**Comment by MikeHibbert** [comment]
This may be rate limiting thats been introduced since the modules creation. Probably best to ask the Arweave guys on Discord if thats has been added.
