### ISSUE TITLE
Throw an error when wallet has insufficient balance.

### ISSUE THREAD

**Issue by fabianriewe** [MikeHibbert/arweave-python-client#9]
I ran into the problem where my wallet had insufficient balance for sending a transaction. When sending the request, the server returned 200 OK but the status of the transaction was always 404 Not Found. It took me some time to figure out, that the sum of reward and quantity was higher than my actual balance. We could implement a check before sending a transaction and throw an error when the sum of quantity and reward is higher than the wallets balance. Any thoughts on this?

Kind regards,
Fabian

**Comment by MikeHibbert** [comment]
Yes sounds like a good idea, Although I did point this out to the guys at Arweave some to time ago and they didn't think this was and issue :)

Frankly, if it makes like more simple go a head and I'll include it.

I'm looking into implementing some unit tests not the project is becoming more than just a quick and dirty solution so if you want to include any feel free

**Comment by fabianriewe** [comment]
Alright, I will go ahead and create some PRs including unittests and the balance feature. This package will be heavily used by upcoming project of mine, including ArVerify (https://github.com/ArVerify).
